### PR TITLE
feature(uxd): update UI to match wireframe designs

### PR DESCRIPTION
**Pull request by mindreeper2420**
update the UI to match the UXD wireframes. visuals to come later.

### CODE REVIEW

**Comment by invincibleJai** [comment]
@pmuir Login screen is completely changed and as per my knowledge stack and component analyses should be in login screen itself i.e user need not login to view it. with current changes it can be viewed  post login. Login screen:
screen shot 2017-03-17 at 8 04 43 am

Post login:
screen shot 2017-03-17 at 8 04 16 am

**Comment by mindreeper2420** [comment]
@invincibleJai I'm confused by what you are stating here - stack and component analysis are available before a user logs in. They are just 'below the fold' of the browser window. A user will not need to be logged in to view that information.

**Comment by invincibleJai** [comment]
@pmuir @mindreeper2420 my bad ,sorry Adam login screen looked so perfect din't thought it'll have scroll .

**Comment by mindreeper2420** [comment]
@invincibleJai no worries :-) This is still just based off of the wireframe, so the visual design group may add callouts or some other aspect to notify the user that they can scroll down for additional information. We can also update the layout as we go, if things are not working/feeling right.

**Comment by invincibleJai** [comment]
@mindreeper2420 sure looks good, we just need to have it on landing page itself or some indication to scroll(I know with UX these changes would be incorporated) .

**Comment by mindreeper2420** [comment]
@invincibleJai I can add a little something on the next update to tell the user to scroll down. I'll also be sending future PRs to make it work a lot better on mobile.

**Pull request closed without merging**
